# Generated by Django 5.2.8 on 2025-11-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=20)),
                ('icone_grupo', models.ImageField(upload_to='icones_grupos/')),
            ],
        ),
        migrations.CreateModel(
            name='Orientadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_orientador', models.CharField(max_length=40)),
                ('icone_orientador', models.ImageField(upload_to='icones_orientadores/')),
            ],
        ),
    ]
